/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : FMSTR1.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : FreeMaster
**     Version     : Component 01.107, Driver 01.06, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-01, 17:12, # CodeGen: 14
**     Abstract    :
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
**     Settings    :
**          Init_SCI                             : QSCI0
**
**          Initialization:
**              Driver interrupt mode            : Mixed interrupt and polling mode
**              Communication device             : JTAG
**              Oscilloscope enabled             : yes
**              Recorder enabled                 : yes
**              Recorder buffer length           : 256
**              Application command enabled      : no
**              Command buffer length            : 16
**              TSA enabled                      : no
**              Read/write memory commands       : yes
**              Read/write variable commands     : no
**              Data buffer length               : 58
**     Contents    :
**         Poll       - void FMSTR1_Poll(void);
**         Recorder   - void FMSTR1_Recorder(void);
**         TriggerRec - void FMSTR1_TriggerRec(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file FMSTR1.c
** @version 01.06
** @brief
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
*/         
/*!
**  @addtogroup FMSTR1_module FMSTR1 module documentation
**  @{
*/         

/* MODULE FMSTR1. */

#include "FMSTR1.h"

/*
** ===================================================================
**     Method      :  FMSTR1_Init (component FreeMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*
void FMSTR1_Init(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/*
** ===================================================================
**     Method      :  FMSTR1_Poll (component FreeMaster)
**     Description :
**         In the poll-driven or short interrupt modes, this function
**         handles the protocol decoding and execution. In the
**         poll-driven mode, this function also handles the SCI
**         communication. In the long interrupt mode, this function
**         compiles as an empty function and may still be called.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void FMSTR1_Poll(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/*
** ===================================================================
**     Method      :  FMSTR1_Isr (component FreeMaster)
**
**     Description :
**         Main SCI/JTAG Interrupt handler call. This Interrupt Service 
**         Routine handles the interrupts for the FreeMASTER driver.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*
void FMSTR1_Isr(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/*
** ===================================================================
**     Method      :  FMSTR1_Recorder (component FreeMaster)
**     Description :
**         Recorder worker routine. This returns quickly if recorder is
**         not running, otherwise it calls quite lengthy recorder
**         routine which does all the recorder work (sampling,
**         triggering). 
**         This method is enabled only if the Recorder property is
**         enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void FMSTR1_Recorder(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/*
** ===================================================================
**     Method      :  FMSTR1_TriggerRec (component FreeMaster)
**     Description :
**         Pull the trigger of the recorder. This function starts the
**         post-trigger stop countdown.
**         This method is enabled only if the Recorder property is
**         enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void FMSTR1_TriggerRec(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/* END FMSTR1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
