/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : freemaster_cfg.h
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Version     : Component 01.107, Driver 01.06, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-01, 17:12, # CodeGen: 14
**     Abstract    :
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file freemaster_cfg.h                                                  
** @version 01.06
** @brief
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
*/         
/*!
**  @addtogroup freemaster_cfg_module freemaster_cfg module documentation
**  @{
*/         

#ifndef __FREEMASTER_CFG_H
#define __FREEMASTER_CFG_H
/* Include generated configuration from the PE PMBus component */
#include "freemaster_cfggen.h"

/* Write your own configuration of the FreeMASTER driver here */


#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/

