/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : INT_RX_REG.h
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : InterruptVector
**     Version     : Component 02.023, Driver 01.16, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-01, 17:12, # CodeGen: 14
**     Abstract    :
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
**     Settings    :
**         Interrupt vector            : INT_RX_REG
**         Handle name                 : FMSTR1_Isr
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file INT_RX_REG.h
** @version 01.16
** @brief
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
*/         
/*!
**  @addtogroup INT_RX_REG_module INT_RX_REG module documentation
**  @{
*/         

#ifndef __INT_RX_REG
#define __INT_RX_REG

/* MODULE INT_RX_REG. */

#include "PE_Types.h"

extern void FMSTR1_Isr(void);

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see INT_RX_REG.c file for more information).
** ===================================================================
*/
void FMSTR1_Isr(void);

/* END INT_RX_REG. */

#endif /* ifndef __INT_RX_REG */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
