/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_Const.h
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : PE_Const
**     Version     : Driver 01.02
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-01, 10:34, # CodeGen: 0
**     Abstract    :
**         This component "PE_Const" contains internal definitions
**         of the constants.
**     Settings    :
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file PE_Const.h
** @version 01.02
** @brief
**         This component "PE_Const" contains internal definitions
**         of the constants.
*/         
/*!
**  @addtogroup PE_Const_module PE_Const module documentation
**  @{
*/         

#ifndef __PE_Const_H
#define __PE_Const_H

#ifdef __cplusplus
extern "C" {
#endif

/* Constants for detecting running mode */
#define HIGH_SPEED        0x00U        /* High speed */
#define LOW_SPEED         0x01U        /* Low speed */
#define SLOW_SPEED        0x02U        /* Slow speed */

/* Reset cause constants */
#define RSTSRC_POR        0x04U        /* Power-on reset */
#define RSTSRC_PIN        0x08U        /* External reset bit */
#define RSTSRC_COP_LOR    0x10U        /* COP loss of reference reset */
#define RSTSRC_COP_CPU    0x20U        /* CPU time-out reset */
#define RSTSRC_SWR        0x40U        /* Software reset */
#define RSTSRC_EZPORT     0x80U        /* EzPort reset */

/* Memory modes */
#define INT_EXT_MODE      0x00U        /* Internal & external memory mode */
#define EXT_MODE          0x01U        /* External memory mode */

#ifdef __cplusplus
}
#endif

#endif /* _PE_Const_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
