/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PWMA.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : Init_eFlexPWM
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-16, 17:56, # CodeGen: 121
**     Abstract    :
**          This file implements the eFlexPWM (PWMA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PWMA
**          Device                                         : PWMA
**          Settings                                       : 
**            Submodule 0                                  : Enabled
**              Clock setting                              : 
**                PWM clock source                         : IP Bus clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 100 MHz
**                Init counter value                       : 60536
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 4999
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 200
**                Dead time value 1                        : 200
**                PWM frequency                            : 10.0000 kHz
**                PWM period                               : 100.0000 us
**                PWM dead time 0                          : 2 us
**                PWM dead time 1                          : 2 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 64536
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 999
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select A                       : Raw PWMA input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select B                       : Raw PWMB input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    X Double switching                   : Disabled
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select X                       : Raw PWMX input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**              Output trigger settings                    : 
**                Output trigger 0 source select           : OUT_TRIG0 signal
**                Output trigger 1 source select           : OUT_TRIG1 signal
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Local reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Enabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 1                                  : Enabled
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 100 MHz
**                Init counter value                       : 60536
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 4999
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 200
**                Dead time value 1                        : 200
**                PWM frequency                            : 10.0000 kHz
**                PWM period                               : 100.0000 us
**                PWM dead time 0                          : 2 us
**                PWM dead time 1                          : 2 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 64536
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 999
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select A                       : Raw PWMA input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select B                       : Raw PWMB input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    X Double switching                   : Disabled
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select X                       : Raw PWMX input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**              Output trigger settings                    : 
**                Output trigger 0 source select           : OUT_TRIG0 signal
**                Output trigger 1 source select           : OUT_TRIG1 signal
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master reload signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : High
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 2                                  : Enabled
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 100 MHz
**                Init counter value                       : 60536
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 4999
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 200
**                Dead time value 1                        : 200
**                PWM frequency                            : 10.0000 kHz
**                PWM period                               : 100.0000 us
**                PWM dead time 0                          : 2 us
**                PWM dead time 1                          : 2 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 64536
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 999
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select A                       : Raw PWMA input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select B                       : Raw PWMB input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    X Double switching                   : Disabled
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select X                       : Raw PWMX input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**              Output trigger settings                    : 
**                Output trigger 0 source select           : OUT_TRIG0 signal
**                Output trigger 1 source select           : OUT_TRIG1 signal
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master reload signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 3                                  : Disabled
**            Fault channel 0 protection settings          : 
**              Common fault settings                      : 
**                Input filter                             : Disabled
**                Fault Glitch Stretch                     : Disabled
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**            Fault channel 1 protection settings          : 
**              Common fault settings                      : 
**                Input filter                             : Disabled
**                Fault Glitch Stretch                     : Disabled
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**          Pins                                           : 
**            SM0 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE1/PWMA_0A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE0/PWMA_0B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**              Output trigger 0                           : Disabled
**              Output trigger 1                           : Disabled
**            SM1 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE3/PWMA_1A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE2/PWMA_1B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**              Output trigger 0                           : Disabled
**              Output trigger 1                           : Disabled
**            SM2 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE5/PWMA_2A/XB_IN3
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE4/PWMA_2B/XB_IN2
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**              Output trigger 0                           : Disabled
**              Output trigger 1                           : Disabled
**            SM3 pins                                     : Disabled
**            PWM Faults                                   : 
**              Fault channel 0                            : 
**                Fault 0                                  : Disabled
**                Fault 1                                  : Disabled
**                Fault 2                                  : Disabled
**                Fault 3                                  : Disabled
**              Fault channel 1                            : 
**                Fault 4                                  : Disabled
**                Fault 5                                  : Disabled
**                Fault 6                                  : Disabled
**                Fault 7                                  : Disabled
**            External clock                               : 
**              External clock                             : Disabled
**              External clock frequency                   : 1
**            External force                               : Disabled
**          Interrupts/DMA                                 : 
**            SM0 Interrupts/DMA                           : Enabled
**              Compare interrupt                          : 
**                Interrupt                                : INT_eFlexPWMA_CMP0
**                Interrupt priority                       : default
**                ISR Name                                 : 
**                Compare interrupt 0                      : Disabled
**                Compare interrupt 1                      : Disabled
**                Compare interrupt 2                      : Disabled
**                Compare interrupt 3                      : Disabled
**                Compare interrupt 4                      : Disabled
**                Compare interrupt 5                      : Disabled
**              Capture interrupt                          : 
**                Interrupt                                : INT_eFlexPWMA_CAP
**                Interrupt priority                       : default
**                ISR Name                                 : 
**                Capture A 0 interrupt                    : Disabled
**                Capture A 1 interrupt                    : Disabled
**                Capture B 0 interrupt                    : Disabled
**                Capture B 1 interrupt                    : Disabled
**                Capture X 0 interrupt                    : Disabled
**                Capture X 1 interrupt                    : Disabled
**              Reload interrupt                           : 
**                Interrupt                                : INT_eFlexPWMA_RELOAD0
**                Interrupt priority                       : 1
**                ISR Name                                 : PWM_RELOAD_ISR
**                Reload interrupt                         : Enabled
**              Reload error interrupt                     : 
**                Interrupt                                : INT_eFlexPWMA_RERR
**                Interrupt priority                       : default
**                ISR Name                                 : 
**                SM0 reload error interrupt               : Disabled
**              DMA settings                               : 
**                DMA for value registers                  : Disabled
**                Selected capture FIFO watermarks         : OR'ed together
**                Capture FIFO read DMA request            : Disabled
**                Capture A 0 FIFO DMA                     : Disabled
**                Capture A 1 FIFO DMA                     : Disabled
**                Capture B 0 FIFO DMA                     : Disabled
**                Capture B 1 FIFO DMA                     : Disabled
**                Capture X 0 FIFO DMA                     : Disabled
**                Capture X 1 FIFO DMA                     : Disabled
**            SM1 Interrupts/DMA                           : Disabled
**            SM2 Interrupts/DMA                           : Disabled
**            SM3 Interrupts/DMA                           : Disabled
**            Fault interrupt                              : 
**              Interrupt                                  : INT_eFlexPWMA_FAULT
**              Interrupt priority                         : default
**              ISR Name                                   : 
**              Channel 0 fault 0 interrupt                : Disabled
**              Channel 0 fault 1 interrupt                : Disabled
**              Channel 0 fault 2 interrupt                : Disabled
**              Channel 0 fault 3 interrupt                : Disabled
**              Channel 1 Fault 0 interrupt                : Disabled
**              Channel 1 Fault 1 interrupt                : Disabled
**              Channel 1 Fault 2 interrupt                : Disabled
**              Channel 1 Fault 3 interrupt                : Disabled
**          Initialization                                 : 
**            Load values after init into SM0              : no
**            Load values after init into SM1              : no
**            Load values after init into SM2              : no
**            Load values after init into SM3              : no
**            Enable peripheral clock for SM0              : yes
**            Enable peripheral clock for SM1              : yes
**            Enable peripheral clock for SM2              : yes
**            Enable peripheral clock for SM3              : no
**            Fault channel 0 test                         : No simulated fault
**            Fault channel 1 test                         : No simulated fault
**            Fault flag clearing                          : 
**              Fault channel 0 flag 0                     : Clear
**              Fault channel 0 flag 1                     : Clear
**              Fault channel 0 flag 2                     : Clear
**              Fault channel 0 flag 3                     : Clear
**              Fault channel 1 flag 0                     : Clear
**              Fault channel 1 flag 1                     : Clear
**              Fault channel 1 flag 2                     : Clear
**              Fault channel 1 flag 3                     : Clear
**            Monitor PLL mode                             : Do not monitor PLL
**            Call Init method                             : yes
**     Contents    :
**         Init - void PWMA_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file PWMA.c
** @version 01.00
** @brief
**          This file implements the eFlexPWM (PWMA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PWMA_module PWMA module documentation
**  @{
*/         

/* MODULE PWMA. */

#include "PWMA.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  PWMA_Init (component Init_eFlexPWM)
**     Description :
**         This method initializes registers of the eFlexPWM module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PWMA_Init(void)
{
  /* PWMA_MCTRL: IPOL&=~7,RUN&=~7,CLDOK|=7,LDOK&=~7 */
  clrSetReg16Bits(PWMA_MCTRL, 0x7707U, 0x70U); 
  /* PWMA_SM0INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWMA_SM0INTEN, 0x00U);       
  /* PWMA_SM1INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWMA_SM1INTEN, 0x00U);       
  /* PWMA_SM2INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWMA_SM2INTEN, 0x00U);       
  /* PWMA_FCTRL0: FLVL=0,FAUTO=0,FSAFE=0,FIE=0 */
  setReg16(PWMA_FCTRL0, 0x00U);         
  /* PWMA_FCTRL1: FLVL=0,FAUTO=0,FSAFE=0,FIE=0 */
  setReg16(PWMA_FCTRL1, 0x00U);         
  /* PWMA_SM0OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=1,POLB=0,POLX=0,??=0,??=0,PWMAFS=2,PWMBFS=0,PWMXFS=0 */
  setReg16(PWMA_SM0OCTRL, 0x0420U);     
  /* PWMA_SM1OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=1,POLB=0,POLX=0,??=0,??=0,PWMAFS=2,PWMBFS=0,PWMXFS=0 */
  setReg16(PWMA_SM1OCTRL, 0x0420U);     
  /* PWMA_SM2OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=1,POLB=0,POLX=0,??=0,??=0,PWMAFS=2,PWMBFS=2,PWMXFS=0 */
  setReg16(PWMA_SM2OCTRL, 0x0428U);     
  /* PWMA_SM0INIT: INIT=0xEC78 */
  setReg16(PWMA_SM0INIT, 0xEC78U);      
  /* PWMA_SM1INIT: INIT=0xEC78 */
  setReg16(PWMA_SM1INIT, 0xEC78U);      
  /* PWMA_SM2INIT: INIT=0xEC78 */
  setReg16(PWMA_SM2INIT, 0xEC78U);      
  /* PWMA_SM0CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=0,FRCEN=1,FORCE=0,FORCE_SEL=0,RELOAD_SEL=0,CLK_SEL=0 */
  setReg16(PWMA_SM0CTRL2, 0x80U);       
  /* PWMA_SM1CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=1,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=1,FRCEN=0,FORCE=0,FORCE_SEL=1,RELOAD_SEL=1,CLK_SEL=2 */
  setReg16(PWMA_SM1CTRL2, 0x110EU);     
  /* PWMA_SM2CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=1,FRCEN=0,FORCE=0,FORCE_SEL=1,RELOAD_SEL=1,CLK_SEL=2 */
  setReg16(PWMA_SM2CTRL2, 0x010EU);     
  /* PWMA_SM0CTRL: LDFQ=0,HALF=0,FULL=1,DT=0,??=0,PRSC=0,??=0,LDMOD=0,DBLX=0,DBLEN=0 */
  setReg16(PWMA_SM0CTRL, 0x0400U);      
  /* PWMA_SM1CTRL: LDFQ=0,HALF=0,FULL=1,DT=0,??=0,PRSC=0,??=0,LDMOD=0,DBLX=0,DBLEN=0 */
  setReg16(PWMA_SM1CTRL, 0x0400U);      
  /* PWMA_SM2CTRL: LDFQ=0,HALF=0,FULL=1,DT=0,??=0,PRSC=0,??=0,LDMOD=0,DBLX=0,DBLEN=0 */
  setReg16(PWMA_SM2CTRL, 0x0400U);      
  /* PWMA_SM0TCTRL: PWAOT0=0,PWBOT1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWMA_SM0TCTRL, 0x00U);       
  /* PWMA_SM1TCTRL: PWAOT0=0,PWBOT1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWMA_SM1TCTRL, 0x00U);       
  /* PWMA_SM2TCTRL: PWAOT0=0,PWBOT1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWMA_SM2TCTRL, 0x00U);       
  /* PWMA_SM0VAL0: VAL0=0 */
  setReg16(PWMA_SM0VAL0, 0x00U);        
  /* PWMA_SM0VAL1: VAL1=0x1387 */
  setReg16(PWMA_SM0VAL1, 0x1387U);      
  /* PWMA_SM0VAL2: VAL2=0xFC18 */
  setReg16(PWMA_SM0VAL2, 0xFC18U);      
  /* PWMA_SM0VAL3: VAL3=0x03E7 */
  setReg16(PWMA_SM0VAL3, 0x03E7U);      
  /* PWMA_SM0VAL4: VAL4=0 */
  setReg16(PWMA_SM0VAL4, 0x00U);        
  /* PWMA_SM0VAL5: VAL5=0 */
  setReg16(PWMA_SM0VAL5, 0x00U);        
  /* PWMA_SM1VAL0: VAL0=0 */
  setReg16(PWMA_SM1VAL0, 0x00U);        
  /* PWMA_SM1VAL1: VAL1=0x1387 */
  setReg16(PWMA_SM1VAL1, 0x1387U);      
  /* PWMA_SM1VAL2: VAL2=0xFC18 */
  setReg16(PWMA_SM1VAL2, 0xFC18U);      
  /* PWMA_SM1VAL3: VAL3=0x03E7 */
  setReg16(PWMA_SM1VAL3, 0x03E7U);      
  /* PWMA_SM1VAL4: VAL4=0 */
  setReg16(PWMA_SM1VAL4, 0x00U);        
  /* PWMA_SM1VAL5: VAL5=0 */
  setReg16(PWMA_SM1VAL5, 0x00U);        
  /* PWMA_SM2VAL0: VAL0=0 */
  setReg16(PWMA_SM2VAL0, 0x00U);        
  /* PWMA_SM2VAL1: VAL1=0x1387 */
  setReg16(PWMA_SM2VAL1, 0x1387U);      
  /* PWMA_SM2VAL2: VAL2=0xFC18 */
  setReg16(PWMA_SM2VAL2, 0xFC18U);      
  /* PWMA_SM2VAL3: VAL3=0x03E7 */
  setReg16(PWMA_SM2VAL3, 0x03E7U);      
  /* PWMA_SM2VAL4: VAL4=0 */
  setReg16(PWMA_SM2VAL4, 0x00U);        
  /* PWMA_SM2VAL5: VAL5=0 */
  setReg16(PWMA_SM2VAL5, 0x00U);        
  /* PWMA_SM0FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM0FRACVAL1, 0x00U);    
  /* PWMA_SM0FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM0FRACVAL2, 0x00U);    
  /* PWMA_SM0FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM0FRACVAL3, 0x00U);    
  /* PWMA_SM0FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM0FRACVAL4, 0x00U);    
  /* PWMA_SM0FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM0FRACVAL5, 0x00U);    
  /* PWMA_SM1FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM1FRACVAL1, 0x00U);    
  /* PWMA_SM1FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM1FRACVAL2, 0x00U);    
  /* PWMA_SM1FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM1FRACVAL3, 0x00U);    
  /* PWMA_SM1FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM1FRACVAL4, 0x00U);    
  /* PWMA_SM1FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM1FRACVAL5, 0x00U);    
  /* PWMA_SM2FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM2FRACVAL1, 0x00U);    
  /* PWMA_SM2FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM2FRACVAL2, 0x00U);    
  /* PWMA_SM2FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM2FRACVAL3, 0x00U);    
  /* PWMA_SM2FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM2FRACVAL4, 0x00U);    
  /* PWMA_SM2FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWMA_SM2FRACVAL5, 0x00U);    
  /* PWMA_SM0FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWMA_SM0FRCTRL, 0x00U);      
  /* PWMA_SM1FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWMA_SM1FRCTRL, 0x00U);      
  /* PWMA_SM2FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWMA_SM2FRCTRL, 0x00U);      
  /* PWMA_SM0DISMAP0: ??=1,??=1,??=1,??=1,DIS0X=0x0F,DIS0B=0x0F,DIS0A=0x0F */
  setReg16(PWMA_SM0DISMAP0, 0xFFFFU);   
  /* PWMA_SM0DISMAP1: ??=1,??=1,??=1,??=1,DIS1X=0x0F,DIS1B=0x0F,DIS1A=0x0F */
  setReg16(PWMA_SM0DISMAP1, 0xFFFFU);   
  /* PWMA_SM1DISMAP0: ??=1,??=1,??=1,??=1,DIS0X=0x0F,DIS0B=0x0F,DIS0A=0x0F */
  setReg16(PWMA_SM1DISMAP0, 0xFFFFU);   
  /* PWMA_SM1DISMAP1: ??=1,??=1,??=1,??=1,DIS1X=0x0F,DIS1B=0x0F,DIS1A=0x0F */
  setReg16(PWMA_SM1DISMAP1, 0xFFFFU);   
  /* PWMA_SM2DISMAP0: ??=1,??=1,??=1,??=1,DIS0X=0x0F,DIS0B=0x0F,DIS0A=0x0F */
  setReg16(PWMA_SM2DISMAP0, 0xFFFFU);   
  /* PWMA_SM2DISMAP1: ??=1,??=1,??=1,??=1,DIS1X=0x0F,DIS1B=0x0F,DIS1A=0x0F */
  setReg16(PWMA_SM2DISMAP1, 0xFFFFU);   
  /* PWMA_SM0DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0xC8 */
  setReg16(PWMA_SM0DTCNT0, 0xC8U);      
  /* PWMA_SM0DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0xC8 */
  setReg16(PWMA_SM0DTCNT1, 0xC8U);      
  /* PWMA_SM1DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0xC8 */
  setReg16(PWMA_SM1DTCNT0, 0xC8U);      
  /* PWMA_SM1DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0xC8 */
  setReg16(PWMA_SM1DTCNT1, 0xC8U);      
  /* PWMA_SM2DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0xC8 */
  setReg16(PWMA_SM2DTCNT0, 0xC8U);      
  /* PWMA_SM2DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0xC8 */
  setReg16(PWMA_SM2DTCNT1, 0xC8U);      
  /* PWMA_SM0CAPTCOMPA: EDGCNTA=0,EDGCMPA=0 */
  setReg16(PWMA_SM0CAPTCOMPA, 0x00U);   
  /* PWMA_SM0CAPTCOMPB: EDGCNTB=0,EDGCMPB=0 */
  setReg16(PWMA_SM0CAPTCOMPB, 0x00U);   
  /* PWMA_SM0CAPTCOMPX: EDGCNTX=0,EDGCMPX=0 */
  setReg16(PWMA_SM0CAPTCOMPX, 0x00U);   
  /* PWMA_SM1CAPTCOMPA: EDGCNTA=0,EDGCMPA=0 */
  setReg16(PWMA_SM1CAPTCOMPA, 0x00U);   
  /* PWMA_SM1CAPTCOMPB: EDGCNTB=0,EDGCMPB=0 */
  setReg16(PWMA_SM1CAPTCOMPB, 0x00U);   
  /* PWMA_SM1CAPTCOMPX: EDGCNTX=0,EDGCMPX=0 */
  setReg16(PWMA_SM1CAPTCOMPX, 0x00U);   
  /* PWMA_SM2CAPTCOMPA: EDGCNTA=0,EDGCMPA=0 */
  setReg16(PWMA_SM2CAPTCOMPA, 0x00U);   
  /* PWMA_SM2CAPTCOMPB: EDGCNTB=0,EDGCMPB=0 */
  setReg16(PWMA_SM2CAPTCOMPB, 0x00U);   
  /* PWMA_SM2CAPTCOMPX: EDGCNTX=0,EDGCMPX=0 */
  setReg16(PWMA_SM2CAPTCOMPX, 0x00U);   
  /* PWMA_FFILT0: GSTR=0,??=0,??=0,??=0,??=0,FILT_CNT=0,FILT_PER=0 */
  setReg16(PWMA_FFILT0, 0x00U);         
  /* PWMA_FFILT1: GSTR=0,??=0,??=0,??=0,??=0,FILT_CNT=0,FILT_PER=0 */
  setReg16(PWMA_FFILT1, 0x00U);         
  /* PWMA_MASK: ??=0,??=0,??=0,??=0,MASKA&=~7,MASKB&=~7,MASKX&=~7 */
  clrReg16Bits(PWMA_MASK, 0xF777U);     
  /* PWMA_SWCOUT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SM2OUT23=0,SM2OUT45=0,SM1OUT23=0,SM1OUT45=0,SM0OUT23=0,SM0OUT45=0 */
  clrReg16Bits(PWMA_SWCOUT, 0xFF3FU);   
  /* PWMA_DTSRCSEL: SM2SEL23=0,SM2SEL45=0,SM1SEL23=0,SM1SEL45=0,SM0SEL23=0,SM0SEL45=0 */
  clrReg16Bits(PWMA_DTSRCSEL, 0x0FFFU); 
  /* PWMA_MCTRL2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,MONPLL=0 */
  setReg16(PWMA_MCTRL2, 0x00U);         
  /* PWMA_OUTEN: ??=0,??=0,??=0,??=0,PWMA_EN|=7,PWMB_EN|=7,PWMX_EN&=~7 */
  clrSetReg16Bits(PWMA_OUTEN, 0xF007U, 0x0770U); 
  /* PWMA_SM0CAPTCTRLA: CA1CNT=0,CA0CNT=0,CFAWM=0,EDGCNTA_EN=0,INP_SELA=0,EDGA1=0,EDGA0=0,ONESHOTA=0,ARMA=0 */
  setReg16(PWMA_SM0CAPTCTRLA, 0x00U);   
  /* PWMA_SM0CAPTCTRLB: CB1CNT=0,CB0CNT=0,CFBWM=0,EDGCNTB_EN=0,INP_SELB=0,EDGB1=0,EDGB0=0,ONESHOTB=0,ARMB=0 */
  setReg16(PWMA_SM0CAPTCTRLB, 0x00U);   
  /* PWMA_SM0CAPTCTRLX: CX1CNT=0,CX0CNT=0,CFXWM=0,EDGCNTX_EN=0,INP_SELX=0,EDGX1=0,EDGX0=0,ONESHOTX=0,ARMX=0 */
  setReg16(PWMA_SM0CAPTCTRLX, 0x00U);   
  /* PWMA_SM1CAPTCTRLA: CA1CNT=0,CA0CNT=0,CFAWM=0,EDGCNTA_EN=0,INP_SELA=0,EDGA1=0,EDGA0=0,ONESHOTA=0,ARMA=0 */
  setReg16(PWMA_SM1CAPTCTRLA, 0x00U);   
  /* PWMA_SM1CAPTCTRLB: CB1CNT=0,CB0CNT=0,CFBWM=0,EDGCNTB_EN=0,INP_SELB=0,EDGB1=0,EDGB0=0,ONESHOTB=0,ARMB=0 */
  setReg16(PWMA_SM1CAPTCTRLB, 0x00U);   
  /* PWMA_SM1CAPTCTRLX: CX1CNT=0,CX0CNT=0,CFXWM=0,EDGCNTX_EN=0,INP_SELX=0,EDGX1=0,EDGX0=0,ONESHOTX=0,ARMX=0 */
  setReg16(PWMA_SM1CAPTCTRLX, 0x00U);   
  /* PWMA_SM2CAPTCTRLA: CA1CNT=0,CA0CNT=0,CFAWM=0,EDGCNTA_EN=0,INP_SELA=0,EDGA1=0,EDGA0=0,ONESHOTA=0,ARMA=0 */
  setReg16(PWMA_SM2CAPTCTRLA, 0x00U);   
  /* PWMA_SM2CAPTCTRLB: CB1CNT=0,CB0CNT=0,CFBWM=0,EDGCNTB_EN=0,INP_SELB=0,EDGB1=0,EDGB0=0,ONESHOTB=0,ARMB=0 */
  setReg16(PWMA_SM2CAPTCTRLB, 0x00U);   
  /* PWMA_SM2CAPTCTRLX: CX1CNT=0,CX0CNT=0,CFXWM=0,EDGCNTX_EN=0,INP_SELX=0,EDGX1=0,EDGX0=0,ONESHOTX=0,ARMX=0 */
  setReg16(PWMA_SM2CAPTCTRLX, 0x00U);   
  /* PWMA_MCTRL: IPOL&=~7,RUN=0,LDOK=0 */
  clrReg16Bits(PWMA_MCTRL, 0x7F0FU);    
  /* PWMA_FSTS0: FHALF=0,FFPIN=0x0F,FFULL=0,FFLAG=0x0F */
  setReg16(PWMA_FSTS0, 0x0F0FU);        
  /* PWMA_FSTS1: FHALF=0,FFPIN=0x0F,FFULL=0,FFLAG=0x0F */
  setReg16(PWMA_FSTS1, 0x0F0FU);        
  /* PWMA_FCTRL0: FLVL=0,FAUTO=0,FSAFE=0,FIE=0 */
  setReg16(PWMA_FCTRL0, 0x00U);         
  /* PWMA_FCTRL1: FLVL=0,FAUTO=0,FSAFE=0,FIE=0 */
  setReg16(PWMA_FCTRL1, 0x00U);         
  /* PWMA_MCTRL: RUN|=7 */
  setReg16Bits(PWMA_MCTRL, 0x0700U);    
  /* PWMA_SM0STS: ??=0,RUF=0,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWMA_SM0STS, 0x3FFFU);       
  /* PWMA_SM0INTEN: ??=0,??=0,REIE=0,RIE=1,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWMA_SM0INTEN, 0x1000U);     
  /* PWMA_SM0DMAEN: ??=0,??=0,??=0,??=0,??=0,??=0,VALDE=0,FAND=0,CAPTDE=0,CA1DE=0,CA0DE=0,CB1DE=0,CB0DE=0,CX1DE=0,CX0DE=0 */
  setReg16(PWMA_SM0DMAEN, 0x00U);       
  /* PWMA_FTST0: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FTEST=0 */
  setReg16(PWMA_FTST0, 0x00U);          
  /* PWMA_FTST1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FTEST=0 */
  setReg16(PWMA_FTST1, 0x00U);          
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      ProcessorExpert.c
**      Events.c
**
** ###################################################################
#if defined(PWM_RELOAD_ISR_FAST_INT)
#pragma interrupt fast
#elif defined(PWM_RELOAD_ISR_VECT_TABLE_ISR_FAST_INT)
#pragma define_section interrupt_fast "interrupt_fast.text"  RX
#pragma section interrupt_fast begin
#pragma interrupt fast
#else
#pragma interrupt saveall
#endif
void PWM_RELOAD_ISR(void)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END PWMA. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
