/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PWMA.h
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : Init_eFlexPWM
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-16, 17:56, # CodeGen: 121
**     Abstract    :
**          This file implements the eFlexPWM (PWMA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PWMA
**          Device                                         : PWMA
**          Settings                                       : 
**            Submodule 0                                  : Enabled
**              Clock setting                              : 
**                PWM clock source                         : IP Bus clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 100 MHz
**                Init counter value                       : 60536
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 4999
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 200
**                Dead time value 1                        : 200
**                PWM frequency                            : 10.0000 kHz
**                PWM period                               : 100.0000 us
**                PWM dead time 0                          : 2 us
**                PWM dead time 1                          : 2 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 64536
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 999
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select A                       : Raw PWMA input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select B                       : Raw PWMB input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    X Double switching                   : Disabled
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select X                       : Raw PWMX input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**              Output trigger settings                    : 
**                Output trigger 0 source select           : OUT_TRIG0 signal
**                Output trigger 1 source select           : OUT_TRIG1 signal
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Local reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Enabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 1                                  : Enabled
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 100 MHz
**                Init counter value                       : 60536
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 4999
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 200
**                Dead time value 1                        : 200
**                PWM frequency                            : 10.0000 kHz
**                PWM period                               : 100.0000 us
**                PWM dead time 0                          : 2 us
**                PWM dead time 1                          : 2 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 64536
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 999
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select A                       : Raw PWMA input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select B                       : Raw PWMB input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    X Double switching                   : Disabled
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select X                       : Raw PWMX input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**              Output trigger settings                    : 
**                Output trigger 0 source select           : OUT_TRIG0 signal
**                Output trigger 1 source select           : OUT_TRIG1 signal
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master reload signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : High
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 2                                  : Enabled
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Module clock                             : 100 MHz
**                Init counter value                       : 60536
**                PWM value 0 - half cycle point           : 0
**                PWM value 1 - counter modulo             : 4999
**                Fractional circuit power up              : Disabled
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 200
**                Dead time value 1                        : 200
**                PWM frequency                            : 10.0000 kHz
**                PWM period                               : 100.0000 us
**                PWM dead time 0                          : 2 us
**                PWM dead time 1                          : 2 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 64536
**                    Fractional value 2 and 3 circuit     : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 999
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select A                       : Raw PWMA input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0
**                    Fractional value 4 and 5 circuit     : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Tristated
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Enabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select B                       : Raw PWMB input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Forced to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    X Double switching                   : Disabled
**                    Channel output                       : Disabled
**                    Fault channel 0                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                    Fault channel 1                      : 
**                      Disable by fault 0                 : yes
**                      Disable by fault 1                 : yes
**                      Disable by fault 2                 : yes
**                      Disable by fault 3                 : yes
**                  E-capture function                     : 
**                    FIFOs water mark level               : 0
**                    Edge counter                         : Disabled
**                    Edge compare                         : 0
**                    Input select X                       : Raw PWMX input signal
**                    Capture 0 circuitry                  : Disabled
**                    Capture 1 circuitry                  : Disabled
**                    Capture circuitry mode               : Free running
**                    Input capture process                : Disabled
**              Output trigger settings                    : 
**                Output trigger 0 source select           : OUT_TRIG0 signal
**                Output trigger 1 source select           : OUT_TRIG1 signal
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master reload signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 3                                  : Disabled
**            Fault channel 0 protection settings          : 
**              Common fault settings                      : 
**                Input filter                             : Disabled
**                Fault Glitch Stretch                     : Disabled
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**            Fault channel 1 protection settings          : 
**              Common fault settings                      : 
**                Input filter                             : Disabled
**                Fault Glitch Stretch                     : Disabled
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Half cycle recovery                      : no
**                Full cycle recovery                      : no
**          Pins                                           : 
**            SM0 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE1/PWMA_0A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE0/PWMA_0B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**              Output trigger 0                           : Disabled
**              Output trigger 1                           : Disabled
**            SM1 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE3/PWMA_1A
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE2/PWMA_1B
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**              Output trigger 0                           : Disabled
**              Output trigger 1                           : Disabled
**            SM2 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE5/PWMA_2A/XB_IN3
**                  PWM/Input capture pin A signal         : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE4/PWMA_2B/XB_IN2
**                  PWM/Input capture pin B signal         : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**              Output trigger 0                           : Disabled
**              Output trigger 1                           : Disabled
**            SM3 pins                                     : Disabled
**            PWM Faults                                   : 
**              Fault channel 0                            : 
**                Fault 0                                  : Disabled
**                Fault 1                                  : Disabled
**                Fault 2                                  : Disabled
**                Fault 3                                  : Disabled
**              Fault channel 1                            : 
**                Fault 4                                  : Disabled
**                Fault 5                                  : Disabled
**                Fault 6                                  : Disabled
**                Fault 7                                  : Disabled
**            External clock                               : 
**              External clock                             : Disabled
**              External clock frequency                   : 1
**            External force                               : Disabled
**          Interrupts/DMA                                 : 
**            SM0 Interrupts/DMA                           : Enabled
**              Compare interrupt                          : 
**                Interrupt                                : INT_eFlexPWMA_CMP0
**                Interrupt priority                       : default
**                ISR Name                                 : 
**                Compare interrupt 0                      : Disabled
**                Compare interrupt 1                      : Disabled
**                Compare interrupt 2                      : Disabled
**                Compare interrupt 3                      : Disabled
**                Compare interrupt 4                      : Disabled
**                Compare interrupt 5                      : Disabled
**              Capture interrupt                          : 
**                Interrupt                                : INT_eFlexPWMA_CAP
**                Interrupt priority                       : default
**                ISR Name                                 : 
**                Capture A 0 interrupt                    : Disabled
**                Capture A 1 interrupt                    : Disabled
**                Capture B 0 interrupt                    : Disabled
**                Capture B 1 interrupt                    : Disabled
**                Capture X 0 interrupt                    : Disabled
**                Capture X 1 interrupt                    : Disabled
**              Reload interrupt                           : 
**                Interrupt                                : INT_eFlexPWMA_RELOAD0
**                Interrupt priority                       : 1
**                ISR Name                                 : PWM_RELOAD_ISR
**                Reload interrupt                         : Enabled
**              Reload error interrupt                     : 
**                Interrupt                                : INT_eFlexPWMA_RERR
**                Interrupt priority                       : default
**                ISR Name                                 : 
**                SM0 reload error interrupt               : Disabled
**              DMA settings                               : 
**                DMA for value registers                  : Disabled
**                Selected capture FIFO watermarks         : OR'ed together
**                Capture FIFO read DMA request            : Disabled
**                Capture A 0 FIFO DMA                     : Disabled
**                Capture A 1 FIFO DMA                     : Disabled
**                Capture B 0 FIFO DMA                     : Disabled
**                Capture B 1 FIFO DMA                     : Disabled
**                Capture X 0 FIFO DMA                     : Disabled
**                Capture X 1 FIFO DMA                     : Disabled
**            SM1 Interrupts/DMA                           : Disabled
**            SM2 Interrupts/DMA                           : Disabled
**            SM3 Interrupts/DMA                           : Disabled
**            Fault interrupt                              : 
**              Interrupt                                  : INT_eFlexPWMA_FAULT
**              Interrupt priority                         : default
**              ISR Name                                   : 
**              Channel 0 fault 0 interrupt                : Disabled
**              Channel 0 fault 1 interrupt                : Disabled
**              Channel 0 fault 2 interrupt                : Disabled
**              Channel 0 fault 3 interrupt                : Disabled
**              Channel 1 Fault 0 interrupt                : Disabled
**              Channel 1 Fault 1 interrupt                : Disabled
**              Channel 1 Fault 2 interrupt                : Disabled
**              Channel 1 Fault 3 interrupt                : Disabled
**          Initialization                                 : 
**            Load values after init into SM0              : no
**            Load values after init into SM1              : no
**            Load values after init into SM2              : no
**            Load values after init into SM3              : no
**            Enable peripheral clock for SM0              : yes
**            Enable peripheral clock for SM1              : yes
**            Enable peripheral clock for SM2              : yes
**            Enable peripheral clock for SM3              : no
**            Fault channel 0 test                         : No simulated fault
**            Fault channel 1 test                         : No simulated fault
**            Fault flag clearing                          : 
**              Fault channel 0 flag 0                     : Clear
**              Fault channel 0 flag 1                     : Clear
**              Fault channel 0 flag 2                     : Clear
**              Fault channel 0 flag 3                     : Clear
**              Fault channel 1 flag 0                     : Clear
**              Fault channel 1 flag 1                     : Clear
**              Fault channel 1 flag 2                     : Clear
**              Fault channel 1 flag 3                     : Clear
**            Monitor PLL mode                             : Do not monitor PLL
**            Call Init method                             : yes
**     Contents    :
**         Init - void PWMA_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file PWMA.h
** @version 01.00
** @brief
**          This file implements the eFlexPWM (PWMA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PWMA_module PWMA module documentation
**  @{
*/         

#ifndef PWMA_H_
#define PWMA_H_

/* MODULE PWMA. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

/* Peripheral base address parameter */
#define PWMA_DEVICE PWMA_BASE_PTR


/*
** ===================================================================
**     Method      :  PWMA_Init (component Init_eFlexPWM)
**     Description :
**         This method initializes registers of the eFlexPWM module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PWMA_Init(void);
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see PWMA.c file for more information).
** ===================================================================
*/
void PWM_RELOAD_ISR(void);


/* END PWMA. */
#endif /* #ifndef __PWMA_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
