/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : QSPI0.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : Init_SPI
**     Version     : Component 01.066, Driver 01.26, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-16, 18:10, # CodeGen: 122
**     Abstract    :
**         This "Init_SPI" Peripheral Inspector implements the
**         Serial Peripheral Interface module (SPI), basic 
**         initialization and settings.
**     Settings    :
**          Component name                                 : QSPI0
**          Device                                         : QSPI0
**          Settings                                       : 
**            Baud rate setting                            : 
**              Clock divisor value                        : 64
**              Baud Divisor Times 2                       : Disabled
**              SPI frequency                              : 1.5625 MHz
**            SPI mode                                     : Master
**            Data size                                    : 8 bits
**            Data shift order                             : MSB first
**            Mode fault checking                          : Enabled
**            Clock polarity                               : falling edge
**            Clock phase                                  : SS edge
**            Wired OR mode                                : Disabled
**          SS data                                        : Low
**          SS open drain                                  : no open drain
**          SS automatic mode                              : Disabled
**          SS direction                                   : Input
**          SS strobe mode                                 : Disabled
**          SS override                                    : Disabled
**          Wait delay                                     : 0
**          Tx FIFO Watermark                              : 0
**          Rx FIFO Watermark                              : 3
**          FIFO enable                                    : Disabled
**          Stop hold                                      : Disabled
**          Pins                                           : 
**            MISO pin                                     : GPIOC8/MISO0/RXD0/XB_IN9
**            MISO pin signal                              : 
**            MOSI pin                                     : GPIOC10/MOSI0/XB_IN5/MISO0
**            MOSI pin signal                              : 
**            SCLK pin                                     : GPIOC9/SCK0/XB_IN4
**            SCLK pin signal                              : 
**            SS pin                                       : GPIOC7/SS0_B/TXD0
**            SS pin signal                                : 
**          Interrupts/DMA                                 : 
**            Receiver full                                : 
**              Interrupt                                  : INT_QSPI0_RCV
**              Receiver interrupt                         : Disabled
**              Error interrupt                            : Disabled
**              Interrupt priority                         : default
**              ISR name                                   : 
**            Transmitter empty                            : 
**              Interrupt                                  : INT_QSPI0_XMIT
**              Transmitter interrupt                      : Disabled
**              Interrupt priority                         : default
**              ISR name                                   : 
**            DMA                                          : 
**              Receive DMA                                : Disabled
**              Transmit DMA                               : Disabled
**          Initialization                                 : 
**            Call Init method                             : yes
**            Enable peripheral clock                      : yes
**            Enable SPI module                            : yes
**     Contents    :
**         Init - void QSPI0_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file QSPI0.c
** @version 01.26
** @brief
**         This "Init_SPI" Peripheral Inspector implements the
**         Serial Peripheral Interface module (SPI), basic 
**         initialization and settings.
*/         
/*!
**  @addtogroup QSPI0_module QSPI0 module documentation
**  @{
*/         

/* MODULE QSPI0. */

#include "QSPI0.h"

/*
** ===================================================================
**     Method      :  QSPI0_Init (component Init_SPI)
**     Description :
**         This method initializes registers of the SPI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void QSPI0_Init(void)
{
  /* QSPI0_SPSCR: SPE=0 */
  clrReg16Bits(QSPI0_SPSCR, 0x20U);    /* Disable device */ 
  /* QSPI0_SPDSR: WOM=0,TDMAEN=0,RDMAEN=0,BD2X=0,SSB_IN=0,SSB_DATA=0,SSB_ODM=0,SSB_AUTO=0,SSB_DDR=0,SSB_STRB=0,SSB_OVER=0,SPR3=0,DS=7 */
  setReg16(QSPI0_SPDSR, 0x07U);        /* Set data size and control register */ 
  /* QSPI0_SPWAIT: ??=0,??=0,??=0,WAIT=0 */
  setReg16(QSPI0_SPWAIT, 0x00U);       /* Set word delay register */ 
  /* QSPI0_SPFIFO: ??=0,TFCNT=0,??=0,RFCNT=0,??=0,TFWM=0,??=0,RFWM=3,??=0,FIFO_ENA=0 */
  setReg16(QSPI0_SPFIFO, 0x0CU);       /* Set FIFO control register */ 
  /* QSPI0_SPCTL2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SHEN=0 */
  setReg16(QSPI0_SPCTL2, 0x00U);       /* Set control register */ 
  /* QSPI0_SPSCR: SPR=5,DSO=0,ERRIE=0,MODFEN=1,SPRIE=0,SPMSTR=1,CPOL=1,CPHA=0,SPE=0,SPTIE=0,SPRF=0,OVRF=0,MODF=0,SPTE=0 */
  setReg16(QSPI0_SPSCR, 0xA580U);      /* Set control register */ 
  getReg(QSPI0_SPSCR);
  getReg(QSPI0_SPDRR);                 /* Clear flags */
  /* QSPI0_SPSCR: SPE=1 */
  setReg16Bits(QSPI0_SPSCR, 0x20U);    /* Enable device */ 
}

/* END QSPI0. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
