/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : QSPI0.h
**     Project     : ProcessorExpert
**     Processor   : MC56F84789VLL
**     Component   : Init_SPI
**     Version     : Component 01.066, Driver 01.26, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-07-16, 18:10, # CodeGen: 122
**     Abstract    :
**         This "Init_SPI" Peripheral Inspector implements the
**         Serial Peripheral Interface module (SPI), basic 
**         initialization and settings.
**     Settings    :
**          Component name                                 : QSPI0
**          Device                                         : QSPI0
**          Settings                                       : 
**            Baud rate setting                            : 
**              Clock divisor value                        : 64
**              Baud Divisor Times 2                       : Disabled
**              SPI frequency                              : 1.5625 MHz
**            SPI mode                                     : Master
**            Data size                                    : 8 bits
**            Data shift order                             : MSB first
**            Mode fault checking                          : Enabled
**            Clock polarity                               : falling edge
**            Clock phase                                  : SS edge
**            Wired OR mode                                : Disabled
**          SS data                                        : Low
**          SS open drain                                  : no open drain
**          SS automatic mode                              : Disabled
**          SS direction                                   : Input
**          SS strobe mode                                 : Disabled
**          SS override                                    : Disabled
**          Wait delay                                     : 0
**          Tx FIFO Watermark                              : 0
**          Rx FIFO Watermark                              : 3
**          FIFO enable                                    : Disabled
**          Stop hold                                      : Disabled
**          Pins                                           : 
**            MISO pin                                     : GPIOC8/MISO0/RXD0/XB_IN9
**            MISO pin signal                              : 
**            MOSI pin                                     : GPIOC10/MOSI0/XB_IN5/MISO0
**            MOSI pin signal                              : 
**            SCLK pin                                     : GPIOC9/SCK0/XB_IN4
**            SCLK pin signal                              : 
**            SS pin                                       : GPIOC7/SS0_B/TXD0
**            SS pin signal                                : 
**          Interrupts/DMA                                 : 
**            Receiver full                                : 
**              Interrupt                                  : INT_QSPI0_RCV
**              Receiver interrupt                         : Disabled
**              Error interrupt                            : Disabled
**              Interrupt priority                         : default
**              ISR name                                   : 
**            Transmitter empty                            : 
**              Interrupt                                  : INT_QSPI0_XMIT
**              Transmitter interrupt                      : Disabled
**              Interrupt priority                         : default
**              ISR name                                   : 
**            DMA                                          : 
**              Receive DMA                                : Disabled
**              Transmit DMA                               : Disabled
**          Initialization                                 : 
**            Call Init method                             : yes
**            Enable peripheral clock                      : yes
**            Enable SPI module                            : yes
**     Contents    :
**         Init - void QSPI0_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file QSPI0.h
** @version 01.26
** @brief
**         This "Init_SPI" Peripheral Inspector implements the
**         Serial Peripheral Interface module (SPI), basic 
**         initialization and settings.
*/         
/*!
**  @addtogroup QSPI0_module QSPI0 module documentation
**  @{
*/         

#ifndef __QSPI0
#define __QSPI0

/* MODULE QSPI0. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "Cpu.h"

/* PESL device mapping  */
#define QSPI0_DEVICE QSPI0

void QSPI0_Init(void);
/*
** ===================================================================
**     Method      :  QSPI0_Init (component Init_SPI)
**     Description :
**         This method initializes registers of the SPI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END QSPI0. */

#endif /* ifndef __QSPI0 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
